# Generated by Django 6.0.2 on 2026-03-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/covers/')),
                ('cover_image_url', models.URLField(blank=True, default='', help_text='External URL for cover image (used when no file is uploaded).', max_length=500)),
                ('cover_image_credit', models.CharField(blank=True, default='', help_text='Attribution text for the cover image (e.g. "Photo by John Doe on Unsplash").', max_length=255)),
                ('cover_image_credit_url', models.URLField(blank=True, default='', help_text='URL to the photographer profile or image source page.', max_length=500)),
                ('excerpt_es', models.TextField(help_text='Resumen corto en español (1-2 oraciones).')),
                ('excerpt_en', models.TextField(help_text='Short summary in English (1-2 sentences).')),
                ('content_es', models.TextField(blank=True, default='', help_text='Contenido completo del artículo en HTML (español).')),
                ('content_en', models.TextField(blank=True, default='', help_text='Full article content in HTML (English).')),
                ('content_json_es', models.JSONField(blank=True, default=dict, help_text='Structured JSON content in Spanish (intro, sections, conclusion, cta).')),
                ('content_json_en', models.JSONField(blank=True, default=dict, help_text='Structured JSON content in English (intro, sections, conclusion, cta).')),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of {name, url} objects for consulted sources.')),
                ('category', models.CharField(blank=True, default='', help_text='Category slug for filtering (e.g. adopcion, cuidado-animal, salud-animal).', max_length=50)),
                ('read_time_minutes', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes.')),
                ('is_featured', models.BooleanField(default=False, help_text='Pin this post as the featured/hero post on the blog listing.')),
                ('author', models.CharField(blank=True, choices=[('tuhuella-team', 'Mi Huella Team'), ('laura-blanco', 'Laura Blanco')], default='tuhuella-team', help_text='Author profile slug (tuhuella-team, laura-blanco).', max_length=50)),
                ('meta_title_es', models.CharField(blank=True, default='', help_text='SEO title override in Spanish.', max_length=255)),
                ('meta_title_en', models.CharField(blank=True, default='', help_text='SEO title override in English.', max_length=255)),
                ('meta_description_es', models.TextField(blank=True, default='', help_text='SEO meta description in Spanish.')),
                ('meta_description_en', models.TextField(blank=True, default='', help_text='SEO meta description in English.')),
                ('meta_keywords_es', models.CharField(blank=True, default='', help_text='Comma-separated SEO keywords in Spanish.', max_length=500)),
                ('meta_keywords_en', models.CharField(blank=True, default='', help_text='Comma-separated SEO keywords in English.', max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
