# Generated by Django 6.0.2 on 2026-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0003_faqtopic_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAmountOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Donation Amount Option',
                'verbose_name_plural': 'Donation Amount Options',
                'ordering': ['order', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipAmountOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sponsorship Amount Option',
                'verbose_name_plural': 'Sponsorship Amount Options',
                'ordering': ['order', 'amount'],
            },
        ),
    ]
