# Generated by Django 6.0.2 on 2026-03-25 18:08

import django.db.models.deletion
import django_attachments.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0006_notificationlog_is_read'),
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_es', models.TextField()),
                ('description_en', models.TextField(blank=True)),
                ('requirements_es', models.TextField(blank=True)),
                ('requirements_en', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('photographer', 'Photographer'), ('shelter_helper', 'Shelter Helper'), ('driver', 'Driver / Transporter'), ('veterinary_volunteer', 'Veterinary Volunteer'), ('social_media', 'Community Manager'), ('event_coordinator', 'Event Coordinator'), ('foster_home', 'Foster Home'), ('fundraiser', 'Fundraiser')], max_length=30)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='evidence_gallery',
            field=django_attachments.fields.GalleryField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_evidence', to='django_attachments.library'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='gallery',
            field=django_attachments.fields.GalleryField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelter_gallery', to='django_attachments.library'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='description_es',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='StrategicAlly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description_es', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('ally_type', models.CharField(choices=[('veterinary', 'Veterinary Clinic'), ('company', 'Company'), ('ngo', 'NGO'), ('government', 'Government'), ('media', 'Media'), ('other', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', django_attachments.fields.SingleImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ally_logo', to='django_attachments.library')),
            ],
            options={
                'verbose_name_plural': 'strategic allies',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
