# Generated by Django 6.0.2 on 2026-03-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0007_volunteerposition_campaign_evidence_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerposition',
            name='category',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('shelter_helper', 'Shelter Helper'), ('driver', 'Driver / Transporter'), ('veterinary_volunteer', 'Veterinary Volunteer'), ('social_media', 'Community Manager'), ('event_coordinator', 'Event Coordinator'), ('foster_home', 'Foster Home'), ('fundraiser', 'Fundraiser'), ('educator', 'Educator'), ('designer', 'Graphic Designer'), ('translator', 'Translator'), ('dog_walker', 'Dog Walker')], max_length=30),
        ),
    ]
