# Generated by Django 6.0.2 on 2026-03-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0010_add_animal_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
