# Generated by Django 6.0.2 on 2026-03-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0012_add_terms_accepted_at'),
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['species', 'size', 'status'], name='animal_species_size_status'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status', 'created_at'], name='animal_status_created'),
        ),
    ]
