# Generated by Django 6.0.2 on 2026-03-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0013_add_animal_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
