# Generated by Django 6.0.2 on 2026-04-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0016_blogpost_cover_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_dewormed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='last_vet_checkup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='medical_notes_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='medical_notes_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sterilized_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccinated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnimalDiseaseScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_key', models.CharField(choices=[('distemper', 'distemper'), ('parvovirus', 'parvovirus'), ('ehrlichia', 'ehrlichia'), ('leptospirosis', 'leptospirosis'), ('heartworm', 'heartworm'), ('fiv', 'fiv'), ('felv', 'felv'), ('panleukopenia', 'panleukopenia'), ('fip', 'fip'), ('calicivirus', 'calicivirus')], max_length=32)),
                ('result', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('not_tested', 'Not tested')], default='not_tested', max_length=12)),
                ('tested_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_screenings', to='base_feature_app.animal')),
            ],
            options={
                'ordering': ['disease_key'],
                'unique_together': {('animal', 'disease_key')},
            },
        ),
    ]
