# Generated by Django 6.0.2 on 2026-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0017_animal_is_dewormed_animal_last_vet_checkup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('adopter', 'Adopter'), ('shelter_admin', 'Shelter Admin'), ('veterinarian', 'Veterinarian'), ('web_manager', 'Web Manager'), ('admin', 'Admin')], default='adopter', max_length=20),
        ),
    ]
