# Generated by Django 6.0.2 on 2026-04-19 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0018_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAdoptionFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=16)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups_as_adopter', to=settings.AUTH_USER_MODEL)),
                ('adoption_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='base_feature_app.adoptionapplication')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='base_feature_app.animal')),
                ('assigned_veterinarian', models.ForeignKey(blank=True, limit_choices_to={'role': 'veterinarian'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups_as_vet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('checkup', 'Checkup'), ('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('observation', 'Observation'), ('incident', 'Incident')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('body_es', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('attachment_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_entries', to='base_feature_app.animal')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_entries', to='base_feature_app.postadoptionfollowup')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='postadoptionfollowup',
            index=models.Index(fields=['status', 'scheduled_date'], name='base_featur_status_73d748_idx'),
        ),
    ]
