# Generated by Django 6.0.2 on 2026-04-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_approval_status(apps, schema_editor):
    Campaign = apps.get_model('base_feature_app', 'Campaign')
    Campaign.objects.filter(status__in=['active', 'completed']).update(approval_status='approved')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0019_postadoptionfollowup_clinicalhistoryentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_approval_status, noop_reverse),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_messages', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base_feature_app.campaign')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['campaign', 'created_at'], name='base_featur_campaig_4f3e07_idx')],
            },
        ),
    ]
