# Generated by Django 6.0.4 on 2026-05-03 18:19

import django.db.models.deletion
import django_attachments.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0021_platform_support_content'),
        ('django_attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shelter_name', models.CharField(max_length=200)),
                ('description_es', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('legal_name', models.CharField(max_length=300)),
                ('tax_id', models.CharField(max_length=50)),
                ('legal_representative_name', models.CharField(max_length=200)),
                ('legal_representative_id', models.CharField(max_length=50)),
                ('motivation', models.TextField()),
                ('previous_experience', models.TextField(blank=True)),
                ('capacity_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_applications', to=settings.AUTH_USER_MODEL)),
                ('created_shelter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='base_feature_app.shelter')),
                ('documents', django_attachments.fields.GalleryField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelter_application_docs', to='django_attachments.library')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shelter_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'under_review'])), fields=('applicant',), name='unique_active_shelter_application_per_user')],
            },
        ),
    ]
