# Generated by Django 6.0.4 on 2026-05-03 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_feature_app', '0022_shelterapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='shelters/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'ogg'])]),
        ),
    ]
