import type {
  ActivityEvent,
  AdopterIntent,
  Animal,
  BlogPost,
  BlogPostAdmin,
  BlogPostDetail,
  Campaign,
  Donation,
  Favorite,
  Payment,
  ProfileStats,
  Shelter,
  ShelterInvite,
  Sponsorship,
  StrategicAlly,
  AdoptionApplication,
  UpdatePost,
  User,
  VolunteerPosition,
} from '../types';

const joined = (iso: string) => iso;

export const mockUser: User = {
  id: 1,
  email: 'adopter@example.com',
  first_name: 'Carlos',
  last_name: 'Pérez',
  phone: '3001234567',
  city: 'Bogotá',
  role: 'adopter',
  is_staff: false,
  is_active: true,
  date_joined: joined('2025-06-01T10:00:00Z'),
};

export const mockShelterAdmin: User = {
  id: 2,
  email: 'shelter@example.com',
  first_name: 'María',
  last_name: 'López',
  phone: '3009876543',
  city: 'Medellín',
  role: 'shelter_admin',
  is_staff: false,
  is_active: true,
  date_joined: joined('2025-08-15T12:00:00Z'),
};

export const mockAdminUser: User = {
  id: 99,
  email: 'admin@mihuella.com',
  first_name: 'Admin',
  last_name: 'Plataforma',
  phone: '3000000000',
  city: 'Bogotá',
  role: 'admin',
  is_staff: true,
  is_active: true,
  date_joined: joined('2024-01-01T08:00:00Z'),
};

export const mockShelters: Shelter[] = [
  {
    id: 1,
    name: 'Patitas Felices',
    legal_name: 'Fundación Patitas Felices',
    description: 'Refugio dedicado al rescate de animales en Bogotá',
    city: 'Bogotá',
    address: 'Calle 45 #12-30',
    phone: '3001112233',
    email: 'info@patitasfelices.org',
    website: 'https://patitasfelices.example.org',
    verification_status: 'verified',
    verified_at: '2026-01-15T10:00:00Z',
    is_verified: true,
    owner_email: 'shelter@example.com',
    logo_url: 'http://example.com/logo-patitas.png',
    cover_image_url: 'http://example.com/cover-patitas.jpg',
    gallery_urls: ['http://example.com/s1.jpg', 'http://example.com/s2.jpg'],
    created_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 2,
    name: 'Hogar Animal',
    description: 'Centro de adopción en Medellín',
    city: 'Medellín',
    verification_status: 'pending',
    verified_at: null,
    is_verified: false,
    owner_email: 'hogar@example.com',
    created_at: '2026-02-01T08:00:00Z',
  },
  {
    id: 3,
    name: 'Refugio Costa Norte',
    legal_name: 'ASOC Costa Norte',
    description: 'En revisión documental',
    city: 'Barranquilla',
    verification_status: 'rejected',
    verified_at: null,
    is_verified: false,
    owner_email: 'costa@example.com',
    created_at: '2026-02-20T08:00:00Z',
  },
];

/** Fila base para favoritos (alineada con FavoriteSerializer / página favoritos). */
export function makeFavorite(overrides: Partial<Favorite> = {}): Favorite {
  return {
    id: 1,
    animal: 10,
    animal_name: 'Luna',
    animal_species: 'dog',
    breed: 'Labrador',
    age_range: 'young',
    size: 'medium',
    gender: 'female',
    is_vaccinated: true,
    is_sterilized: true,
    status: 'published',
    shelter_name: 'Patitas Felices',
    shelter_city: 'Bogotá',
    thumbnail_url: null,
    note: '',
    created_at: '2026-01-12T08:00:00Z',
    ...overrides,
  };
}

export const mockFavorites: Favorite[] = [
  makeFavorite({ id: 1, animal: 1, animal_name: 'Luna', note: 'Familia con patio' }),
  makeFavorite({
    id: 2,
    animal: 2,
    animal_name: 'Milo',
    animal_species: 'cat',
    breed: 'Siamés',
    age_range: 'adult',
    size: 'small',
    gender: 'male',
    is_sterilized: false,
    shelter_name: 'Patitas Felices',
    created_at: '2026-01-18T10:00:00Z',
  }),
  makeFavorite({
    id: 3,
    animal: 4,
    animal_name: 'Coco',
    animal_species: 'other',
    breed: 'Conejo enano',
    age_range: 'adult',
    status: 'in_process',
    shelter_name: 'Hogar Animal',
    shelter_city: 'Medellín',
    created_at: '2026-02-01T11:00:00Z',
  }),
];

export const mockAnimals: Animal[] = [
  {
    id: 1,
    name: 'Luna',
    species: 'dog',
    breed: 'Labrador',
    age_range: 'young',
    gender: 'female',
    size: 'medium',
    description: 'Perrita cariñosa y juguetona',
    status: 'published',
    is_vaccinated: true,
    is_sterilized: true,
    is_house_trained: true,
    good_with_kids: 'yes',
    good_with_dogs: 'yes',
    good_with_cats: 'unknown',
    energy_level: 'medium',
    weight: 18.5,
    coat_color: 'Golden',
    microchip_id: 'MC-001-LUNA',
    intake_date: '2025-11-01',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    shelter_city: 'Bogotá',
    gallery_urls: ['http://example.com/luna1.jpg', 'http://example.com/luna2.jpg'],
    created_at: '2026-01-10T12:00:00Z',
  },
  {
    id: 2,
    name: 'Milo',
    species: 'cat',
    breed: 'Siamés',
    age_range: 'adult',
    gender: 'male',
    size: 'small',
    description: 'Gato tranquilo e independiente',
    status: 'published',
    is_vaccinated: true,
    is_sterilized: false,
    is_house_trained: false,
    good_with_kids: 'unknown',
    good_with_dogs: 'unknown',
    good_with_cats: 'unknown',
    energy_level: 'low',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    shelter_city: 'Bogotá',
    gallery_urls: ['http://example.com/milo1.jpg'],
    created_at: '2026-01-15T14:00:00Z',
  },
  {
    id: 3,
    name: 'Rocky',
    species: 'dog',
    breed: 'Mestizo',
    age_range: 'puppy',
    gender: 'male',
    size: 'large',
    description: 'Cachorro enérgico que necesita un hogar con jardín',
    special_needs: 'Necesita ejercicio diario',
    status: 'published',
    is_vaccinated: false,
    is_sterilized: false,
    is_house_trained: false,
    good_with_kids: 'no',
    good_with_dogs: 'yes',
    good_with_cats: 'no',
    energy_level: 'high',
    shelter: 2,
    shelter_name: 'Hogar Animal',
    shelter_city: 'Medellín',
    gallery_urls: [],
    created_at: '2026-02-05T09:00:00Z',
  },
  {
    id: 4,
    name: 'Coco',
    species: 'other',
    breed: 'Conejo enano',
    age_range: 'adult',
    gender: 'unknown',
    size: 'small',
    description: 'Conejo sociable, usa jaula amplia',
    status: 'in_process',
    is_vaccinated: true,
    is_sterilized: true,
    is_house_trained: true,
    good_with_kids: 'yes',
    good_with_dogs: 'no',
    good_with_cats: 'unknown',
    energy_level: 'medium',
    shelter: 2,
    shelter_name: 'Hogar Animal',
    shelter_city: 'Medellín',
    gallery_urls: ['http://example.com/coco1.jpg'],
    created_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 5,
    name: 'Sasha',
    species: 'dog',
    breed: 'Pastor alemán',
    age_range: 'senior',
    gender: 'female',
    size: 'large',
    description: 'Ya encontró familia — referencia estado adoptado',
    status: 'adopted',
    is_vaccinated: true,
    is_sterilized: true,
    is_house_trained: true,
    good_with_kids: 'yes',
    good_with_dogs: 'yes',
    good_with_cats: 'no',
    energy_level: 'low',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    shelter_city: 'Bogotá',
    gallery_urls: [],
    created_at: '2025-06-01T09:00:00Z',
  },
  {
    id: 6,
    name: 'Borrador Feliz',
    species: 'cat',
    breed: 'Común europeo',
    age_range: 'young',
    gender: 'female',
    size: 'small',
    description: 'Aún no publicado en listados públicos',
    status: 'draft',
    is_vaccinated: false,
    is_sterilized: false,
    is_house_trained: false,
    good_with_kids: 'unknown',
    good_with_dogs: 'unknown',
    good_with_cats: 'unknown',
    energy_level: 'high',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    shelter_city: 'Bogotá',
    gallery_urls: [],
    created_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 7,
    name: 'Toby Archivado',
    species: 'dog',
    breed: 'Beagle',
    age_range: 'adult',
    gender: 'male',
    size: 'medium',
    description: 'Archivado por duplicidad de ficha',
    status: 'archived',
    is_vaccinated: true,
    is_sterilized: true,
    is_house_trained: true,
    good_with_kids: 'yes',
    good_with_dogs: 'yes',
    good_with_cats: 'yes',
    energy_level: 'medium',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    created_at: '2025-01-01T08:00:00Z',
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 1,
    title: 'Fondo Médico de Emergencia',
    description: 'Ayúdanos a cubrir los costos médicos de animales rescatados',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    status: 'active',
    goal_amount: '500000.00',
    raised_amount: '125000.00',
    progress_percentage: 25,
    cover_image_url: 'http://example.com/campaign1.jpg',
    starts_at: '2026-01-01T00:00:00Z',
    ends_at: '2026-06-30T23:59:59Z',
    created_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 2,
    title: 'Nuevo Refugio',
    description: 'Estamos construyendo un nuevo espacio para más animales',
    shelter: 2,
    shelter_name: 'Hogar Animal',
    status: 'draft',
    goal_amount: '2000000.00',
    raised_amount: '0.00',
    progress_percentage: 0,
    cover_image_url: null,
    starts_at: null,
    ends_at: null,
    created_at: '2026-02-10T08:00:00Z',
  },
  {
    id: 3,
    title: 'Esterilización masiva marzo',
    description: 'Meta casi alcanzada',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    status: 'active',
    goal_amount: '800000.00',
    raised_amount: '760000.00',
    progress_percentage: 95,
    cover_image_url: 'http://example.com/campaign-esteril.jpg',
    evidence_gallery_urls: ['http://example.com/ev1.jpg'],
    starts_at: '2026-03-01T00:00:00Z',
    ends_at: '2026-03-31T23:59:59Z',
    created_at: '2026-02-28T08:00:00Z',
  },
  {
    id: 4,
    title: 'Campaña cerrada exitosamente',
    description: 'Gracias a todos',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    status: 'completed',
    goal_amount: '300000.00',
    raised_amount: '310000.00',
    progress_percentage: 100,
    cover_image_url: null,
    starts_at: '2025-11-01T00:00:00Z',
    ends_at: '2026-01-31T23:59:59Z',
    created_at: '2025-10-25T08:00:00Z',
  },
  {
    id: 5,
    title: 'Pausada por auditoría',
    shelter: 2,
    shelter_name: 'Hogar Animal',
    status: 'paused',
    goal_amount: '100000.00',
    raised_amount: '20000.00',
    progress_percentage: 20,
    cover_image_url: null,
    starts_at: '2026-01-15T00:00:00Z',
    ends_at: '2026-12-31T23:59:59Z',
    created_at: '2026-01-14T08:00:00Z',
  },
];

export const mockDonations: Donation[] = [
  {
    id: 1,
    user: 1,
    user_email: 'adopter@example.com',
    destination: 'campaign',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    shelter_city: 'Bogotá',
    campaign: 1,
    campaign_title: 'Fondo Médico de Emergencia',
    amount: '50000.00',
    status: 'paid',
    message: 'Espero que esto ayude',
    paid_at: '2026-01-20T15:30:00Z',
    created_at: '2026-01-20T15:00:00Z',
  },
  {
    id: 2,
    user: 1,
    user_email: 'adopter@example.com',
    destination: 'shelter',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    shelter_city: 'Bogotá',
    campaign: null,
    campaign_title: null,
    amount: '25000.00',
    status: 'pending',
    message: null,
    paid_at: null,
    created_at: '2026-03-28T09:00:00Z',
  },
  {
    id: 3,
    user: 1,
    user_email: 'adopter@example.com',
    destination: 'platform',
    shelter: null,
    shelter_name: null,
    campaign: null,
    campaign_title: null,
    amount: '10000.00',
    status: 'failed',
    created_at: '2026-03-27T18:00:00Z',
  },
];

export const mockSponsorships: Sponsorship[] = [
  {
    id: 1,
    user: 1,
    user_email: 'adopter@example.com',
    animal: 1,
    animal_name: 'Luna',
    shelter_name: 'Patitas Felices',
    amount: '30000.00',
    frequency: 'monthly',
    status: 'active',
    started_at: '2026-01-15T10:00:00Z',
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 2,
    user: 1,
    user_email: 'adopter@example.com',
    animal: 2,
    animal_name: 'Milo',
    animal_species: 'cat',
    amount: '50000.00',
    frequency: 'one_time',
    status: 'paused',
    started_at: '2025-12-01T10:00:00Z',
    created_at: '2025-12-01T10:00:00Z',
  },
  {
    id: 3,
    user: 1,
    animal: 3,
    animal_name: 'Rocky',
    amount: '20000.00',
    frequency: 'monthly',
    status: 'canceled',
    started_at: '2025-06-01T10:00:00Z',
    created_at: '2025-06-01T10:00:00Z',
  },
];

export const mockAdoptionApplications: AdoptionApplication[] = [
  {
    id: 1,
    animal: 1,
    animal_name: 'Luna',
    animal_species: 'dog',
    shelter_name: 'Patitas Felices',
    user: 1,
    user_email: 'adopter@example.com',
    status: 'submitted',
    form_answers: { reason: 'Quiero darle un hogar a Luna', has_garden: true },
    notes: 'Tengo experiencia con perros',
    reviewed_at: null,
    created_at: '2026-01-25T11:00:00Z',
  },
  {
    id: 2,
    animal: 2,
    animal_name: 'Milo',
    animal_species: 'cat',
    shelter_name: 'Patitas Felices',
    user: 1,
    user_email: 'adopter@example.com',
    status: 'reviewing',
    form_answers: {},
    notes: '',
    reviewed_at: null,
    created_at: '2026-02-01T09:00:00Z',
  },
  {
    id: 3,
    animal: 3,
    animal_name: 'Rocky',
    shelter_name: 'Hogar Animal',
    user: 1,
    user_email: 'adopter@example.com',
    status: 'interview',
    form_answers: { visit_preference: 'weekend' },
    created_at: '2026-02-10T14:00:00Z',
  },
  {
    id: 4,
    animal: 5,
    animal_name: 'Sasha',
    shelter_name: 'Patitas Felices',
    user: 1,
    user_email: 'adopter@example.com',
    status: 'approved',
    form_answers: {},
    reviewed_at: '2026-02-20T16:00:00Z',
    created_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 5,
    animal: 4,
    animal_name: 'Coco',
    shelter_name: 'Hogar Animal',
    user: 1,
    user_email: 'adopter@example.com',
    status: 'rejected',
    form_answers: {},
    reviewed_at: '2026-03-01T12:00:00Z',
    created_at: '2026-02-25T11:00:00Z',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 1,
    donation: 1,
    sponsorship: null,
    provider: 'wompi',
    provider_reference: 'ref-paid-001',
    amount: '50000.00',
    status: 'approved',
    paid_at: '2026-01-20T15:30:00Z',
    metadata: {},
    created_at: '2026-01-20T15:00:00Z',
  },
  {
    id: 2,
    donation: null,
    sponsorship: 1,
    provider: 'wompi',
    provider_reference: 'ref-pend-002',
    amount: '30000.00',
    status: 'pending',
    paid_at: null,
    metadata: {},
    created_at: '2026-03-19T14:00:00Z',
  },
  {
    id: 3,
    donation: 2,
    sponsorship: null,
    provider: 'wompi',
    provider_reference: 'ref-decl-003',
    amount: '10000.00',
    status: 'declined',
    paid_at: null,
    metadata: { reason: 'insufficient_funds' },
    created_at: '2026-03-18T08:00:00Z',
  },
  {
    id: 4,
    donation: 2,
    sponsorship: null,
    provider: 'wompi',
    provider_reference: 'ref-void-004',
    amount: '20000.00',
    status: 'voided',
    paid_at: null,
    metadata: {},
    created_at: '2026-03-10T10:00:00Z',
  },
  {
    id: 5,
    donation: 3,
    sponsorship: null,
    provider: 'wompi',
    provider_reference: 'ref-err-005',
    amount: '15000.00',
    status: 'error',
    paid_at: null,
    metadata: {},
    created_at: '2026-03-05T11:00:00Z',
  },
];

export const mockVolunteerPositions: VolunteerPosition[] = [
  {
    id: 1,
    title: 'Fotógrafo de animales',
    description: 'Documenta adopciones y el día a día del refugio.',
    requirements: 'Cámara propia',
    category: 'photographer',
    icon: '',
    order: 0,
  },
  {
    id: 2,
    title: 'Paseador de perros',
    description: 'Paseos en parques cercanos.',
    requirements: 'Fines de semana',
    category: 'dog_walker',
    icon: '',
    order: 1,
  },
  {
    id: 3,
    title: 'Ayuda en refugio',
    description: 'Limpieza, alimentación y juego.',
    requirements: 'Disponibilidad 4h/semana',
    category: 'shelter_helper',
    icon: '',
    order: 2,
  },
  {
    id: 4,
    title: 'Conductor de rescates',
    description: 'Traslado de animales a veterinaria.',
    requirements: 'Licencia de conducir',
    category: 'driver',
    icon: '',
    order: 3,
  },
  {
    id: 5,
    title: 'Redes sociales',
    description: 'Crear contenido para Instagram y Facebook.',
    requirements: 'Portfolio básico',
    category: 'social_media',
    icon: '',
    order: 4,
  },
];

export const mockStrategicAllies: StrategicAlly[] = [
  {
    id: 1,
    name: 'VetCare Aliados',
    description: 'Red de clínicas con descuento para adoptantes.',
    logo_url: 'http://example.com/ally-vetcare.png',
    website: 'https://vetcare.example.com',
    ally_type: 'veterinary',
    order: 0,
  },
  {
    id: 2,
    name: 'Tienda Mascotas Unidas',
    description: 'Alimento y accesorios para nuevos hogares.',
    logo_url: 'http://example.com/ally-shop.png',
    website: 'https://mascotas.example.com',
    ally_type: 'retail',
    order: 1,
  },
];

export const mockUpdatePosts: UpdatePost[] = [
  {
    id: 1,
    title: 'Luna ya come sola en su cuenco',
    content: 'Seguimos con su adaptación.',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    campaign: 1,
    animal: 1,
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
  },
  {
    id: 2,
    title: 'Campaña de vacunas — 80% logrado',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    campaign: 3,
    created_at: '2026-03-15T08:00:00Z',
  },
];

export const mockAdopterIntent: AdopterIntent = {
  id: 1,
  user: 1,
  user_email: 'adopter@example.com',
  user_name: 'Carlos Pérez',
  preferences: { species: 'dog', size: 'medium', energy: 'medium' },
  description: 'Busco perro mediano, bueno con niños',
  status: 'active',
  visibility: 'public',
  created_at: '2026-01-05T10:00:00Z',
  updated_at: '2026-01-05T10:00:00Z',
};

export const mockShelterInvite: ShelterInvite = {
  id: 1,
  shelter: 1,
  shelter_name: 'Patitas Felices',
  adopter_intent: 1,
  adopter_email: 'adopter@example.com',
  message: 'Nos encantaría conocerte',
  status: 'pending',
  created_at: '2026-02-01T12:00:00Z',
};

export const mockProfileStats: ProfileStats = {
  applications: {
    total: 5,
    by_status: { submitted: 1, reviewing: 1, interview: 1, approved: 1, rejected: 1 },
  },
  sponsorships: { active_count: 1, total_count: 3 },
  donations: { total_amount: '85000.00', count: 3 },
  favorites: {
    count: 3,
    preview: [
      { id: 1, name: 'Luna', species: 'dog', thumbnail_url: 'http://example.com/t1.jpg' },
      { id: 2, name: 'Milo', species: 'cat', thumbnail_url: null },
    ],
  },
  adopter_intent: { status: 'active', visibility: 'public' },
  shelter_invites: { pending_count: 2 },
};

export const mockActivityEvents: ActivityEvent[] = [
  {
    type: 'application',
    animal_name: 'Luna',
    shelter_name: 'Patitas Felices',
    status: 'submitted',
    date: '2026-01-25T11:00:00Z',
  },
  {
    type: 'donation',
    shelter_name: 'Patitas Felices',
    amount: '50000.00',
    date: '2026-01-20T15:00:00Z',
  },
  {
    type: 'sponsorship',
    animal_name: 'Luna',
    amount: '30000.00',
    date: '2026-01-15T10:00:00Z',
  },
  {
    type: 'favorite',
    animal_name: 'Milo',
    date: '2026-01-18T10:00:00Z',
  },
];

export const mockShelter: Shelter = mockShelters[0];
export const mockAnimal: Animal = mockAnimals[0];
export const mockCampaign: Campaign = mockCampaigns[0];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 1,
    title: 'Guía de adopción responsable',
    slug: 'guia-de-adopcion-responsable',
    cover_image: 'http://example.com/blog1.jpg',
    excerpt: 'Todo lo que necesitas saber para adoptar.',
    category: 'adopcion',
    read_time_minutes: 5,
    is_featured: true,
    author: 'tuhuella-team',
    is_published: true,
    published_at: '2026-03-01T10:00:00Z',
    created_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 2,
    title: 'Cuidados básicos para tu mascota',
    slug: 'cuidados-basicos-para-tu-mascota',
    cover_image: 'http://example.com/blog2.jpg',
    excerpt: 'Consejos esenciales para nuevos dueños.',
    category: 'cuidado-animal',
    read_time_minutes: 8,
    is_featured: false,
    author: 'laura-blanco',
    is_published: true,
    published_at: '2026-03-05T12:00:00Z',
    created_at: '2026-03-05T10:00:00Z',
  },
  {
    id: 3,
    title: 'Voluntariado: primeros pasos',
    slug: 'voluntariado-primeros-pasos',
    cover_image: '',
    excerpt: 'Cómo empezar a ayudar en tu ciudad.',
    category: 'voluntariado',
    read_time_minutes: 6,
    is_featured: false,
    author: 'tuhuella-team',
    is_published: false,
    published_at: null,
    created_at: '2026-03-10T09:00:00Z',
  },
  {
    id: 4,
    title: 'Nutrición para perros senior',
    slug: 'nutricion-perros-senior',
    cover_image: 'http://example.com/blog4.jpg',
    excerpt: 'Ajustes dietéticos recomendados.',
    category: 'nutricion',
    read_time_minutes: 7,
    is_featured: false,
    author: 'laura-blanco',
    is_published: true,
    published_at: '2099-12-01T10:00:00Z',
    created_at: '2026-03-12T08:00:00Z',
  },
];

export const mockBlogPostDetail: BlogPostDetail = {
  ...mockBlogPosts[0],
  cover_image_credit: 'Photo by Example',
  cover_image_credit_url: 'http://example.com/credit',
  content: '<h2>Introducción</h2><p>Contenido del blog.</p>',
  content_json: {
    intro: 'Adoptar es un acto de amor.',
    sections: [
      { type: 'heading', level: 2, text: 'Paso 1' },
      { type: 'paragraph', text: 'Investiga refugios cercanos.' },
    ],
  },
  sources: [{ name: 'OMS Animal', url: 'http://example.com/source' }],
  meta_title: 'Guía de adopción',
  meta_description: 'Todo sobre adopción responsable.',
  meta_keywords: 'adopción, mascotas',
  updated_at: '2026-03-01T10:00:00Z',
};

export const mockBlogPostAdmin: BlogPostAdmin = {
  id: 1,
  title_es: 'Guía de adopción responsable',
  title_en: 'Responsible Adoption Guide',
  slug: 'guia-de-adopcion-responsable',
  cover_image: 'http://example.com/blog1.jpg',
  cover_image_url: '',
  cover_image_display: 'http://example.com/blog1.jpg',
  cover_image_credit: 'Photo by Example',
  cover_image_credit_url: 'http://example.com/credit',
  excerpt_es: 'Todo lo que necesitas saber.',
  excerpt_en: 'Everything you need to know.',
  content_es: '<p>Contenido</p>',
  content_en: '<p>Content</p>',
  content_json_es: { intro: 'Hola', sections: [] },
  content_json_en: { intro: 'Hello', sections: [] },
  sources: [{ name: 'OMS', url: 'http://example.com' }],
  category: 'adopcion',
  read_time_minutes: 5,
  is_featured: true,
  author: 'tuhuella-team',
  meta_title_es: 'Guía',
  meta_title_en: 'Guide',
  meta_description_es: 'Descripción',
  meta_description_en: 'Description',
  meta_keywords_es: 'adopción',
  meta_keywords_en: 'adoption',
  is_published: true,
  published_at: '2026-03-01T10:00:00Z',
  created_at: '2026-03-01T08:00:00Z',
  updated_at: '2026-03-01T10:00:00Z',
};

export const mockBlogPost: BlogPost = mockBlogPosts[0];
