import type {
  Animal,
  BlogPost,
  BlogPostAdmin,
  BlogPostDetail,
  Shelter,
  Campaign,
  Donation,
  Sponsorship,
  AdoptionApplication,
  Favorite,
  User,
} from '../types';

export const mockUser: User = {
  id: 1,
  email: 'adopter@example.com',
  first_name: 'Carlos',
  last_name: 'Pérez',
  phone: '3001234567',
  city: 'Bogotá',
  role: 'adopter',
  is_staff: false,
  is_active: true,
};

export const mockShelterAdmin: User = {
  id: 2,
  email: 'shelter@example.com',
  first_name: 'María',
  last_name: 'López',
  phone: '3009876543',
  city: 'Medellín',
  role: 'shelter_admin',
  is_staff: false,
  is_active: true,
};

export const mockShelters: Shelter[] = [
  {
    id: 1,
    name: 'Patitas Felices',
    legal_name: 'Fundación Patitas Felices',
    description: 'Refugio dedicado al rescate de animales en Bogotá',
    city: 'Bogotá',
    address: 'Calle 45 #12-30',
    phone: '3001112233',
    email: 'info@patitasfelices.org',
    verification_status: 'verified',
    verified_at: '2026-01-15T10:00:00Z',
    is_verified: true,
    owner_email: 'shelter@example.com',
    created_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 2,
    name: 'Hogar Animal',
    description: 'Centro de adopción en Medellín',
    city: 'Medellín',
    verification_status: 'pending',
    verified_at: null,
    is_verified: false,
    owner_email: 'hogar@example.com',
    created_at: '2026-02-01T08:00:00Z',
  },
];

export const mockAnimals: Animal[] = [
  {
    id: 1,
    name: 'Luna',
    species: 'dog',
    breed: 'Labrador',
    age_range: 'young',
    gender: 'female',
    size: 'medium',
    description: 'Perrita cariñosa y juguetona',
    status: 'published',
    is_vaccinated: true,
    is_sterilized: true,
    is_house_trained: true,
    good_with_kids: 'yes',
    good_with_dogs: 'yes',
    good_with_cats: 'unknown',
    energy_level: 'medium',
    weight: 18.5,
    coat_color: 'Golden',
    microchip_id: 'MC-001-LUNA',
    intake_date: '2025-11-01',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    shelter_city: 'Bogotá',
    gallery_urls: ['http://example.com/luna1.jpg', 'http://example.com/luna2.jpg'],
    created_at: '2026-01-10T12:00:00Z',
  },
  {
    id: 2,
    name: 'Milo',
    species: 'cat',
    breed: 'Siamés',
    age_range: 'adult',
    gender: 'male',
    size: 'small',
    description: 'Gato tranquilo e independiente',
    status: 'published',
    is_vaccinated: true,
    is_sterilized: false,
    is_house_trained: false,
    good_with_kids: 'unknown',
    good_with_dogs: 'unknown',
    good_with_cats: 'unknown',
    energy_level: 'low',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    shelter_city: 'Bogotá',
    gallery_urls: ['http://example.com/milo1.jpg'],
    created_at: '2026-01-15T14:00:00Z',
  },
  {
    id: 3,
    name: 'Rocky',
    species: 'dog',
    breed: 'Mestizo',
    age_range: 'puppy',
    gender: 'male',
    size: 'large',
    description: 'Cachorro enérgico que necesita un hogar con jardín',
    special_needs: 'Necesita ejercicio diario',
    status: 'published',
    is_vaccinated: false,
    is_sterilized: false,
    is_house_trained: false,
    good_with_kids: 'no',
    good_with_dogs: 'yes',
    good_with_cats: 'no',
    energy_level: 'high',
    shelter: 2,
    shelter_name: 'Hogar Animal',
    shelter_city: 'Medellín',
    gallery_urls: [],
    created_at: '2026-02-05T09:00:00Z',
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 1,
    title: 'Fondo Médico de Emergencia',
    description: 'Ayúdanos a cubrir los costos médicos de animales rescatados',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    status: 'active',
    goal_amount: '500000.00',
    raised_amount: '125000.00',
    progress_percentage: 25,
    cover_image_url: 'http://example.com/campaign1.jpg',
    starts_at: '2026-01-01T00:00:00Z',
    ends_at: '2026-06-30T23:59:59Z',
    created_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 2,
    title: 'Nuevo Refugio',
    description: 'Estamos construyendo un nuevo espacio para más animales',
    shelter: 2,
    shelter_name: 'Hogar Animal',
    status: 'draft',
    goal_amount: '2000000.00',
    raised_amount: '0.00',
    progress_percentage: 0,
    cover_image_url: null,
    starts_at: null,
    ends_at: null,
    created_at: '2026-02-10T08:00:00Z',
  },
];

export const mockDonations: Donation[] = [
  {
    id: 1,
    user: 1,
    user_email: 'adopter@example.com',
    shelter: 1,
    shelter_name: 'Patitas Felices',
    campaign: 1,
    campaign_title: 'Fondo Médico de Emergencia',
    amount: '50000.00',
    status: 'paid',
    message: 'Espero que esto ayude',
    paid_at: '2026-01-20T15:30:00Z',
    created_at: '2026-01-20T15:00:00Z',
  },
];

export const mockSponsorships: Sponsorship[] = [
  {
    id: 1,
    user: 1,
    user_email: 'adopter@example.com',
    animal: 1,
    animal_name: 'Luna',
    shelter_name: 'Patitas Felices',
    amount: '30000.00',
    frequency: 'monthly',
    status: 'active',
    started_at: '2026-01-15T10:00:00Z',
    created_at: '2026-01-15T10:00:00Z',
  },
];

export const mockAdoptionApplications: AdoptionApplication[] = [
  {
    id: 1,
    animal: 1,
    animal_name: 'Luna',
    shelter_name: 'Patitas Felices',
    user: 1,
    user_email: 'adopter@example.com',
    status: 'submitted',
    form_answers: { reason: 'Quiero darle un hogar a Luna', has_garden: true },
    notes: 'Tengo experiencia con perros',
    reviewed_at: null,
    created_at: '2026-01-25T11:00:00Z',
  },
];

export const mockFavorites: Favorite[] = [
  {
    id: 1,
    animal: 1,
    animal_name: 'Luna',
    animal_species: 'dog',
    shelter_name: 'Patitas Felices',
    created_at: '2026-01-12T08:00:00Z',
  },
  {
    id: 2,
    animal: 2,
    animal_name: 'Milo',
    animal_species: 'cat',
    shelter_name: 'Patitas Felices',
    created_at: '2026-01-18T10:00:00Z',
  },
];

export const mockShelter: Shelter = mockShelters[0];
export const mockAnimal: Animal = mockAnimals[0];
export const mockCampaign: Campaign = mockCampaigns[0];

export const mockBlogPosts: BlogPost[] = [
  {
    id: 1,
    title: 'Guía de adopción responsable',
    slug: 'guia-de-adopcion-responsable',
    cover_image: 'http://example.com/blog1.jpg',
    excerpt: 'Todo lo que necesitas saber para adoptar.',
    category: 'adopcion',
    read_time_minutes: 5,
    is_featured: true,
    author: 'tuhuella-team',
    is_published: true,
    published_at: '2026-03-01T10:00:00Z',
    created_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 2,
    title: 'Cuidados básicos para tu mascota',
    slug: 'cuidados-basicos-para-tu-mascota',
    cover_image: 'http://example.com/blog2.jpg',
    excerpt: 'Consejos esenciales para nuevos dueños.',
    category: 'cuidado-animal',
    read_time_minutes: 8,
    is_featured: false,
    author: 'laura-blanco',
    is_published: true,
    published_at: '2026-03-05T12:00:00Z',
    created_at: '2026-03-05T10:00:00Z',
  },
];

export const mockBlogPostDetail: BlogPostDetail = {
  ...mockBlogPosts[0],
  cover_image_credit: 'Photo by Example',
  cover_image_credit_url: 'http://example.com/credit',
  content: '<h2>Introducción</h2><p>Contenido del blog.</p>',
  content_json: {
    intro: 'Adoptar es un acto de amor.',
    sections: [
      { type: 'heading', level: 2, text: 'Paso 1' },
      { type: 'paragraph', text: 'Investiga refugios cercanos.' },
    ],
  },
  sources: [
    { name: 'OMS Animal', url: 'http://example.com/source' },
  ],
  meta_title: 'Guía de adopción',
  meta_description: 'Todo sobre adopción responsable.',
  meta_keywords: 'adopción, mascotas',
  updated_at: '2026-03-01T10:00:00Z',
};

export const mockBlogPostAdmin: BlogPostAdmin = {
  id: 1,
  title_es: 'Guía de adopción responsable',
  title_en: 'Responsible Adoption Guide',
  slug: 'guia-de-adopcion-responsable',
  cover_image: 'http://example.com/blog1.jpg',
  cover_image_url: '',
  cover_image_display: 'http://example.com/blog1.jpg',
  cover_image_credit: 'Photo by Example',
  cover_image_credit_url: 'http://example.com/credit',
  excerpt_es: 'Todo lo que necesitas saber.',
  excerpt_en: 'Everything you need to know.',
  content_es: '<p>Contenido</p>',
  content_en: '<p>Content</p>',
  content_json_es: { intro: 'Hola', sections: [] },
  content_json_en: { intro: 'Hello', sections: [] },
  sources: [{ name: 'OMS', url: 'http://example.com' }],
  category: 'adopcion',
  read_time_minutes: 5,
  is_featured: true,
  author: 'tuhuella-team',
  meta_title_es: 'Guía',
  meta_title_en: 'Guide',
  meta_description_es: 'Descripción',
  meta_description_en: 'Description',
  meta_keywords_es: 'adopción',
  meta_keywords_en: 'adoption',
  is_published: true,
  published_at: '2026-03-01T10:00:00Z',
  created_at: '2026-03-01T08:00:00Z',
  updated_at: '2026-03-01T10:00:00Z',
};

export const mockBlogPost: BlogPost = mockBlogPosts[0];
